# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='html_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='queue',
            name='download_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
